Repository drashland/website, pull requests merged in 2020-11, with the labels that each got.

#224 docs: Add documentation for the whole create app script
  drash/vue/app.vue
  drash/vue/pages/tutorials/cli/create_app.vue
  drash/vue/pages/tutorials/cli/introduction.vue
  drash/vue/sidebar.vue
Labels: Type: Chore

#231 [#211-request-getall-docs] Add docs for the getAll() method for Drash
  drash/vue/app.vue
  drash/vue/pages/tutorials/requests/get_all_params.vue
Labels: Remark: Approved, Type: Chore

#244 docs: Add youtube link to rhum badges
  assets/bundles/dmm_app.staging.js
  assets/bundles/drash_app.staging.js
  assets/bundles/rhum_app.staging.js
  assets/bundles/sockets_app.staging.js
  index.html
  index.template.html
  rhum/vue/pages/getting_started.vue
  staging/dmm/index.html
  staging/drash/index.html
  staging/rhum/index.html
  staging/sockets/index.html
Labels: Remark: Approved, Type: Chore

#248 docs: Virtual Paths
  drash/example_code/tutorials/servers/serving_virtual_paths/back_end/app.ts
  drash/example_code/tutorials/servers/serving_virtual_paths/back_end/home_resource.ts
  drash/example_code/tutorials/servers/serving_virtual_paths/folder_structure.txt
  drash/example_code/tutorials/servers/serving_virtual_paths/front_end/style.css
  drash/vue/app.vue
  drash/vue/pages/tutorials/servers/serving_virtual_paths.vue
Labels: Priority: High

#232 docs: Remove all instances of openChannel and replace them with on() where needed
  sockets/vue/pages/advanced_tutorials/creating_a_chat_app/part_2.vue
  sockets/vue/pages/tutorials/adding_clients_to_channels.vue
  sockets/vue/pages/tutorials/closing_channels.vue
  sockets/vue/pages/tutorials/opening_channels.vue
  sockets/vue/pages/tutorials/removing_clients_from_channels.vue
  sockets/vue/pages/tutorials/sending_to_specific_clients.vue
Labels: Type: Chore

#274 feat: Add example applications to sidebar
  assets/common/vue/app_root.vue
  assets/common/vue/sidebar.vue
  dmm/vue/app.vue
  drash/vue/app.vue
  rhum/vue/app.vue
  wocket/vue/app.vue
Labels: Type: Enhancement
